# main text of home
name: Cedric Chee
bio: Full stack software engineer at Vintedge and founder of Trinine.

# twitter summary info
description: Cedric Chee is a full stack software engineer at Vintedge and founder of Trinine. He helps companies build web and mobile apps in JavaScript, React, Webpack, Node.js, Android & others.

repository: cedrickchee/personal-website

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/my-profile-pic.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
# resume: true
# resume-external: true
# resume-url: https://google.com/?q=cedric+chee

url: https://cedricchee.com
# your url: http://USERNAME.github.io

permalink: "/:year/:month/:day/:title/"

# To enable google analytics, supply your token below
analytics-google: 'UA-98667456-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: cedricchee # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
twitter: cedric_chee
linkedin: cedricchee
github: cedrickchee
medium: cedric_chee
google: CedricChee
stackoverflow: 206570/cedrickchee
quora: cedric-chee
# instagram: cedrickchee
# pinterest: cedrickchee
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# reddit: cedrickchee
# vimeo: cedrickchee
facebook: cedrickchee
email: cedric+site@invictusbyte.com

authors:
    cedrickchee:
        name: Cedric Chee
        bio: Full stack software engineer at Vintedge and founder of Trinine.
        external-image: false
        picture: assets/images/my-profile-pic.jpg
        twitter: cedric_chee

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
# projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: false

encoding: UTF-8
lang: en-US
branch: gh-pages

gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

jekyll-mentions:
    base_url: https://github.com
